//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public decimal ID_TIPO_DOCUMENTO { get; set; }
        public decimal DOCUMENTO { get; set; }
        public Nullable<decimal> CUIT { get; set; }
        public decimal ID_LOCALIDAD { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> ID_TIPO_PERSONA { get; set; }
        public string LEGAJO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    }
}
