//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectores.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoresModelEntities : DbContext
    {
        public ProyectoresModelEntities()
            : base("name=ProyectoresModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<MotivoBajaReserva> MotivoBajaReserva { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Proyectores> Proyectores { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Salones> Salones { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Tipos_Persona> Tipos_Persona { get; set; }
    }
}
