//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public decimal ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal ID_SALON { get; set; }
        public decimal TIPO_PERSONA { get; set; }
        public Nullable<decimal> ID_PERSONAL { get; set; }
        public Nullable<decimal> ID_ALUMNO { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELACION { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
    }
}
