//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelotest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENU
    {
        public decimal ID { get; set; }
        public decimal ID_Padre { get; set; }
        public decimal ID_Sistema { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public string Icono { get; set; }
        public string Color_Header { get; set; }
        public decimal Orden { get; set; }
    }
}
