//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectores
    {
        public decimal ID { get; set; }
        public string MARCA { get; set; }
        public string SERIAL { get; set; }
        public decimal HDMI { get; set; }
        public string MODELO { get; set; }
        public decimal DISPONIBLE { get; set; }
        public decimal OPERATIVO { get; set; }
    }
}
